name: Release package to Pypi

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/yeti-switch-api
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_dev.txt
    - name: build package
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

