name: Release package to Pypi

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/yeti-switch-api
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements_dev.txt

    - name: build package
      run: python setup.py sdist bdist_wheel
      env:
        RELEASE_VERSION: ${{github.ref}}

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

