name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          setup.cfg
          setup.py
          requirements.txt
    - name: Activate virtualenv
      run: |
        python -m venv .virtualenv
        source .virtualenv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --show-source --statistics
    - name: Check code format with Black
      run: |
        # stop the build if psf/black found not formatted file
        # https://github.com/psf/black
        python -m black . --check
    - name: Build package
      run: |
        python setup.py sdist
        python setup.py bdist_wheel
    - name: Check build
      run: |
        python -m twine check dist/*
